### ISSUE TITLE
{Left, Right, Full} Outer Joins with multiple/complex predicates are not supported

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/hyrise#1436]
#1437 disabled hyrise compiling them, previously they were broken in multiple ways:

* For join statements like `a LEFT JOIN b ON a.a + 5 = b.a`, it executes a cross join and a subsequent scan for `a.a + 5 = b.a`. This possibly discards tuples from `a`, even though they should all survive the left outer join
* For join statements like `a LEFT JOIN b ON a.a = b.a AND a.a = 1` the predicate `a.a = 1` will just be dropped. This means tuple-pairs where `a.a != 1` survive the join.

The correct (as by Postgres(TM)) behaviour is as follows. Consider two tables:

```
T1
a,b
1,1
1,2
3,4

T2
x,y
1,2
3,4
5,6
```

### Correct left join behaviour

`(1, 1)` and `(1,2)` from `T1` surviving joined with nulls:
```
SELECT * FROM T1 LEFT JOIN T2 ON a = 3

1 | 1 | (null) | (null)
1 | 2 | (null) | (null)
3 | 4 | 1 | 2
3 | 4 | 3 | 4
3 | 4 | 5 | 6
```

`(1,2)` from `T2` surviving once, even though the predicate `a = x` matches it with two tuples from `T1` [1]:
```
SELECT * FROM T2 LEFT JOIN T1 ON a = x AND a != 1

1 | 2 | (null) | (null)
3 | 4 | 3 | 4
5 | 6 | (null) | (null)
```

### Correct full join behaviour
First, consider a simple full join:

```
SELECT * FROM T1 FULL JOIN T2 ON a = x

1 | 1 | 1 | 2
1 | 2 | 1 | 2
3 | 4 | 3 | 4
(null) | (null) | 5 | 6
```

Now: an second predicate might introduce additional rows! [1]
```
SELECT * FROM T1 FULL JOIN T2 ON a = x AND a != 3

1 | 1 | 1 | 2
1 | 2 | 1 | 2
3 | 4 | (null) | (null)
(null) | (null) | 5 | 6
(null) | (null) | 3 | 4
```

### How can a combination of Hyrise's existing operators implement this?
Out of my head, I couldn't come up with anything, but I'm probably just tired. [1] means that we cannot go the Join{Hash,SortMerge} + Scan(s) path.

**Comment by Bouncner** [comment]
Did you guys talk to each other?
I think the first case might be better solved with a materialized column with the expr result before executing the join (we can talk next week about this, I think it should be rather easy to include it in the join with your help).
The second issue should be fully  covered with the mutiple-predicate join.

**Comment by mrzzzrm** [comment]
Noticed this just yesterday, so haven't had a chance to talk to anyone yet. Curious to learn about the multi-predicate join.

**Comment by Bouncner** [comment]
Ah right. Forgot which day it is. 😁

**Comment by mrzzzrm** [comment]
After #1482, this can probably be solved for queries like `SELECT * FROM id_int_int_int_100 AS t1 LEFT JOIN id_int_int_int_100 AS t2 ON t1.a >= t2.a AND t1.a > t2.a;`, i.e., those with an AND-chain of simple join predicates. Complex join predicates that perform more operations as part of the join predicate still cannot be supported.

**Comment by mrzzzrm** [comment]
Closing, as we consider joins with complex predicates too obscure to implement support for them preemptively/before we have actually encountered a query requiring them.
